const images = {
    IMAGE_LOGO: require("../images/logo.svg"),
    IMAGE_DECORATION: require("../images/page-shape-elements.svg"),
    IMAGE_HOME_HERO: require("../images/tempImg.svg"),
    IMAGE_HOME_INDEX_MOBILE: require("../images/index-mobile.svg"),
    IMAGE_ABOUT: require("../images/about.png"),
    IMAGE_CONTACT: require("../images/contact.png"),
    IMAGE_RESUME: require("../images/resume.png"),

    IMAGE_ACUTE: require("../images/project/acute.png"),
    IMAGE_ACUTE1: require("../images/project/acute/acute1.png"),
    IMAGE_ACUTE2: require("../images/project/acute/acute2.png"),
    IMAGE_ACUTE3: require("../images/project/acute/acute3.png"),
    IMAGE_ACUTE4: require("../images/project/acute/acute4.png"),
    IMAGE_ACUTE5: require("../images/project/acute/acute5.png"),

    IMAGE_MOBILE: require("../images/project/mobile.png"),
    IMAGE_MOBILE1: require("../images/project/mobile/mobile1.png"),
    IMAGE_MOBILE2: require("../images/project/mobile/mobile2.svg"),
    IMAGE_MOBILE_PAGE1: require("../images/project/mobile/1.png"),
    IMAGE_MOBILE_PAGE2: require("../images/project/mobile/2.png"),
    IMAGE_MOBILE_PAGE3: require("../images/project/mobile/3.png"),
    IMAGE_MOBILE_PAGE4: require("../images/project/mobile/4.png"),
    IMAGE_MOBILE_PAGE5: require("../images/project/mobile/5.png"),
    IMAGE_MOBILE_PAGE6: require("../images/project/mobile/6.png"),
    IMAGE_MOBILE_PAGE7: require("../images/project/mobile/7.png"),
    IMAGE_MOBILE_PAGE8: require("../images/project/mobile/8.png"),
    IMAGE_MOBILE_PAGE9: require("../images/project/mobile/9.png"),
    IMAGE_MOBILE_PAGE10: require("../images/project/mobile/10.png"),
    IMAGE_MOBILE_PAGE11: require("../images/project/mobile/11.png"),
    IMAGE_MOBILE_PAGE12: require("../images/project/mobile/12.png"),

    IMAGE_YUTAR: require("../images/project/yutar.png"),
    IMAGE_YUTAR1: require("../images/project/yutar/yutar1.svg"),
    IMAGE_YUTAR2: require("../images/project/yutar/yutar2.png"),
    IMAGE_YUTAR_PAGE1: require("../images/project/yutar/1.png"),
    IMAGE_YUTAR_PAGE2: require("../images/project/yutar/2.png"),
    IMAGE_YUTAR_PAGE3: require("../images/project/yutar/3.png"),
    IMAGE_YUTAR_PAGE4: require("../images/project/yutar/4.png"),

    IMAGE_FINANCIAL: require("../images/project/financial.png"),
    IMAGE_FINANCIAL1: require("../images/project/financial/landing1.png"),
    IMAGE_FINANCIAL_PALETTE: require("../images/project/financial/palette.png"),
    IMAGE_FINANCIAL_PAGE1: require("../images/project/financial/1.png"),
    IMAGE_FINANCIAL_PAGE2: require("../images/project/financial/2.png"),
    IMAGE_FINANCIAL_PAGE3: require("../images/project/financial/3.png"),
    IMAGE_FINANCIAL_PAGE4: require("../images/project/financial/4.png"),
    IMAGE_FINANCIAL_PAGE5: require("../images/project/financial/5.png"),
    IMAGE_FINANCIAL_PAGE6: require("../images/project/financial/6.png"),
    IMAGE_FINANCIAL_PAGE7: require("../images/project/financial/7.png"),
    IMAGE_FINANCIAL_PAGE8: require("../images/project/financial/8.png"),
    IMAGE_FINANCIAL_PAGE9: require("../images/project/financial/9.png"),


    IMAGE_XPUTER: require("../images/project/xputer.png"),
    IMAGE_XPUTER1: require("../images/project/xputer/landing.png"),
    IMAGE_XPUTER2: require("../images/project/xputer/landing-mobile.png"),
    IMAGE_XPUTER_PAGE1: require("../images/project/xputer/1.png"),
    IMAGE_XPUTER_PAGE2: require("../images/project/xputer/2.png"),


    IMAGE_ESTATE: require("../images/project/estate.png"),
    IMAGE_ESTATE1: require("../images/project/estate/landing.png"),
    IMAGE_ESTATE_PALETTE: require("../images/project/estate/palette.png"),
    IMAGE_ESTATE_PAGE1: require("../images/project/estate/1.png"),
    IMAGE_ESTATE_PAGE2: require("../images/project/estate/2.png"),
    IMAGE_ESTATE_PAGE3: require("../images/project/estate/3.png"),
    IMAGE_ESTATE_PAGE4: require("../images/project/estate/4.png"),
    IMAGE_ESTATE_PAGE5: require("../images/project/estate/5.png"),
    IMAGE_ESTATE_PAGE6: require("../images/project/estate/6.png"),
    IMAGE_ESTATE_PAGE7: require("../images/project/estate/7.png"),
    IMAGE_ESTATE_PAGE8: require("../images/project/estate/8.png"),
    IMAGE_ESTATE_PAGE9: require("../images/project/estate/9.png"),
    IMAGE_ESTATE_PAGE10: require("../images/project/estate/10.png"),
    IMAGE_ESTATE_PAGE11: require("../images/project/estate/11.png"),
    IMAGE_ESTATE_PAGE12: require("../images/project/estate/12.png"),

    IMAGE_GRAPHICS1: require("../images/graphics/1.png"),
    IMAGE_GRAPHICS2: require("../images/graphics/2.png"),
    IMAGE_GRAPHICS3: require("../images/graphics/3.png"),
    IMAGE_GRAPHICS4: require("../images/graphics/4.png"),
    IMAGE_GRAPHICS5: require("../images/graphics/5.png"),
    IMAGE_GRAPHICS6: require("../images/graphics/6.png"),

    IMAGE_PENCILS1: require("../images/pencils/1.png"),
    IMAGE_PENCILS2: require("../images/pencils/2.png"),
    IMAGE_PENCILS3: require("../images/pencils/3.png"),
    IMAGE_PENCILS4: require("../images/pencils/4.png"),
    IMAGE_PENCILS5: require("../images/pencils/5.png"),
    IMAGE_PENCILS6: require("../images/pencils/6.png"),

    IC_TALK: require("../images/icon/talk.svg"),
    IC_TALK_WHITE: require("../images/icon/talk-white.svg"),
    IC_MESSAGE: require("../images/icon/message.svg"),
    IC_MAIL: require("../images/icon/mail.svg"),
    IC_DOWNLOAD: require("../images/icon/download.svg"),
    IC_ARROW: require("../images/icon/arrow.svg"),
    IC_ARROW_WHITE: require("../images/icon/arrow-white.svg"),
    IC_PACK1: require("../images/icon/pack1.svg"),
    IC_PACK2: require("../images/icon/pack2.svg"),
    IC_PACK3: require("../images/icon/pack3.svg"),
    IC_PACK4: require("../images/icon/pack4.svg"),
};

export default images;
